### ISSUE TITLE
System disk usage high when running groth16 solver

### ISSUE THREAD

**Issue by RobQuistNL** [filecoin-project/bellman#100]
I'm benchmarking a lot to see what would be the fastest setup to run a miner - but unfortunately I see this part of the benchmark using a disk I don't want it to use - but I'm not sure how to control it.

This part in the benchmark;
```
2020-07-23T14:23:14.735 INFO filecoin_proofs::api::seal > got groth params (34359738368) while sealing
2020-07-23T14:23:14.735 INFO filecoin_proofs::api::seal > snark_proof:start
2020-07-23T14:23:14.753 INFO bellperson::groth16::prover > Bellperson 0.9.2 is being used!
```

RAM slowly climbs to 128GB with 50% of all cores at 100%.

Once it reaches the 128GB, core usage drops everywhere, and I can see a ton or writes on my OS disk (sdb)

Then after a few minutes it went over to:
```
2020-07-23T14:38:34.473 INFO bellperson::gpu::locks > GPU is available for FFT!
2020-07-23T14:38:40.023 INFO bellperson::gpu::fft > FFT: 1 working device(s) selected.
2020-07-23T14:38:40.025 INFO bellperson::gpu::fft > FFT: Device 0: GeForce GTX 1080 Ti
2020-07-23T14:38:40.025 INFO bellperson::domain > GPU FFT kernel instantiated!
```

and I see a _ton_ of reads on my OS disk (sdb);

```
avg-cpu:  %user   %nice %system %iowait  %steal   %idle
           0,1%    0,0%    0,8%    3,9%    0,0%   95,2%

      tps    kB_read/s    kB_wrtn/s    kB_dscd/s    kB_read    kB_wrtn    kB_dscd Device
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k loop0
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k loop1
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k loop2
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k loop3
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k loop4
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k loop5
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k loop6
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k loop7
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k loop8
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k loop9
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k nvme0n1
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k sda
  5375,00        21,0M         0,0k         0,0k      21,0M       0,0k       0,0k sdb
     0,00         0,0k         0,0k         0,0k       0,0k       0,0k       0,0k sdc
```

The command I used to run the benchmark was like so;
```
env RUST_LOG=info FIL_PROOFS_USE_GPU_COLUMN_BUILDER=1 FIL_PROOFS_USE_GPU_TREE_BUILDER=1 FIL_PROOFS_MAXIMIZE_CACHING=1 FIL_PROOFS_PARENT_CACHE=/mnt/nvme_2tb/filecoin-parents/ FIL_PROOFS_PARAMETER_CACHE=/mnt/nvme_2tb/filecoin-proof-parameters TMPDIR=/mnt/nvme_2tb ./lotus-bench sealing --storage-dir /mnt/nvme_2tb/bench --sector-size 32GiB --save-commit2-input ~/commit2_nvme_64_1080.json 2>&1 | tee bench.log
```

`nvme0n1` is mounted on `/mnt/nvme_2tb`  - and different parts of the benchmark using those disks are reflected in `iostat`.

So, my question is:
1) what is happening on the disk?
2) how can I move it to another disk?

**Comment by RobQuistNL** [comment]
Skimming through the codebases I might be wrong that this is logic inside of `bellman` :thinking: 
Pinging @cryptonemo and @dignifiedquire just in case :)

**Comment by keyvank** [comment]
@RobQuistNL Hi Rob! I believe this is happening because something else is filling your RAM, so the OS needs to use swap files and that leads to a situation where memory load is higher than cpu load which makes CPU utilization less than expected.

**Comment by RobQuistNL** [comment]
It seems that I was kind of tired when I wrote this unit - because you're right. I swore I had my swapfile on my NVMe, but it looks like I did not. Quite sure its the swap being used..... will move it to the NVMe (where its supposed to be). Quite sure its that :) Thanks!

**Comment by RobQuistNL** [comment]
To double check: I'm benchmarking with 32GiB sectors - is it expected to use about 150GB RAM? My 128GB is filled and a small bit goes into SWAP.

I also see my GPU only use 5GB out of available 11. Is that expected? I tried tuning some parameters like these;
```
FIL_PROOFS_MAX_GPU_COLUMN_BATCH_SIZE
FIL_PROOFS_COLUMN_WRITE_BATCH_SIZE
FIL_PROOFS_MAX_GPU_TREE_BATCH_SIZE
```

but they don't seem to have a lot of effect. The value `FIL_PROOFS_SDR_PARENTS_CACHE_SIZE` only affects RAM, I suppose? Not VRAM? Or should I be asking this question here: https://github.com/filecoin-project/rust-fil-proofs :+)

**Comment by keyvank** [comment]
@RobQuistNL I don't know a lot about the RAM usage of rust-fil-proofs tbh, you should probably ask `rust-fil-proofs` guys. But I know the GPU RAM usage should be around that number. It sometimes goes up to 8-9 GB when doing FFT, other than FFT, 5-6GB is enough to fully utilize GPU.

**Comment by RobQuistNL** [comment]
Would it be possible to use more VRAM? Or is this memory usage just fixed for the sector size?

I have another graphics card here with 16GB VRAM and would be nice it I can utilize it all :)

**Comment by keyvank** [comment]
@RobQuistNL Yes, I think we can. Our multigpu impl is not the best in terms of VRAM utilization. I guess you just need to wait for us to improve this :)

**Comment by RobQuistNL** [comment]
Lets see who's faster - you with a pile of more important todo's or my ability to learn Rust and Go ;p 

Thanks for your help so far :)
